import { useState, useEffect, createContext } from 'react';

import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

import ProductCategory from '../components/ProductCategory';
import Filters from '../components/Filters';

export default function Home({ data }) {
  const [products, setProducts] = useState();
  const [selectedProduct, setSelectedProduct] = useState();
  const ProductsContext = createContext();

  useEffect(() => {
    const products = {};
    for (const product of data) {
      if (!products[product.product_name]) {
        products[product.product_name] = [product];
      } else {
        products[product.product_name] = [
          ...products[product.product_name],
          product,
        ];
      }
    }
    setProducts(products);
  }, []);

  const generateProducts = () => {
    return Object.entries(products).map(([key, value]) => {
      return <ProductCategory productName={key} products={value} />;
    });
  };

  return (
    <div>
      <Head>
        <title>Edvora</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <ProductsContext.Provider value={{ products, selectedProduct }}>
          <Filters />
          <section>
            <h1 className={styles.title}>Edvora</h1>
            <h3 className={styles.subtitle}>Products</h3>
            {products && generateProducts()}
          </section>
        </ProductsContext.Provider>
      </main>
    </div>
  );
}

export const getStaticProps = async () => {
  const response = await fetch('https://assessment-edvora.herokuapp.com/');
  const data = await response.json();
  return {
    props: {
      data,
    },
  };
};
